#	Spectral Deluxe for Jekyll (https://github.com/dcsjapan/jekyll-theme-spectral-deluxe)
#	by Dominion (https://www.dcsjapan.com)
#	Free for personal and commercial use under CC-BY-3.0 (https://creativecommons.org/licenses/by/3.0/)
#
#	Based on Spectral (https://html5up.net/spectral)
#	by HTML5 UP (https://html5up.net | @ajlkn)
#	Free for personal and commercial use under CC-BY-3.0 (https://html5up.net/license)

# SITE SETTINGS

title:          Spectral Deluxe

description:    A Jekyll theme based on Spectral by HTML5 UP

url:            "" # the base hostname & protocol for your site, e.g. "http://example.com"
baseurl:        "" # the subpath of your site, e.g. "/blog"

language:       en # See https://www.w3schools.com/tags/ref_language_codes.asp

# THEME SETTINGS

# theme:        jekyll-theme-spectral-deluxe

index_desc:     true # This setting enables use of the site description instead of a page title for the landing page.
                     # Leave it blank to use the page title (or just the site title when the page title is also null).

font_family:         # the font family you want to use for the site; defaults to "'Open Sans', Helvetica, sans-serif".
webfont_url:         # the URL for the webfont you want to use for the site; defaults to Open Sans from Google.
                     # (Include the following weights and styles: 400, 400italic, 600, 600italic, 800, and 800italic.)

banner_image:        # the filename of the site banner image; defaults to 'banner.jpg'.
image_source:        # the path where image files are stored; defaults to '/assets/images/'.
                     # You may specify an external server as an absolute URL, e.g. "https://example.com/assets/".
                     # NOTE: Use '/demo_images/' when building the theme's demo site.

colors:         # Enter hex values in quotes (e.g. "#ffffff" for white) for the settings below to customize the color of...
  body:              # the webpage body
  header:            # the site header
  footer:            # the site footer
  menu:              # the offcanvas menu
  major:             # the "major text" section of the landing page
  recent:            # the "recent posts" section of the landing page
  tiles:             # the "text tiles" section of the landing page
  page:              # the main body of pages and posts
  button:            # the primary buttons (i.e. the ones that are red by default)

custom_css:          # the name of your custom CSS file (e.g. "custom.scss") if you want to use one for this site.
                     # Jekyll will look for the file specified here in the '/assets/css/' directory.
                     # NOTE: Changes to banner image, font family, and background colors may override config settings.

recent_tiles:   3    # the number of tiles in the "recent posts" section of the landing page
                     # (The theme supports a maximum of ten recent posts in this section.)

date_format:    "%B %d, %Y"

excerpt_separator: <!--end_excerpt-->

# SITE OWNER SETTINGS

owner:          Your Name Here

social_icons:   true # This setting enables use the social media icons in the footer. Leave blank to disable icons.
                     # The order of the icons can be changed by rearranging the entries in 'social-media.yml' datafile.

facebook_url:   ""
dribble_url:    ""
github_url:     ""
gitlab_url:     ""
instagram_url:  ""
linkedin_url:   ""
pinterest_url:  ""
slack_url:      ""
twitter_url:    ""
email_url:      ""

# BUILD SETTINGS

sass:
  style: expanded   # NOTE: Use 'compressed' when building the theme's demo site.

# Use these plugins:
plugins:
  - jekyll-liquify

# Include these collections of demo content:
collections:
  demo_pages:
    output: true
    permalink: /spectral/:name/

# Exclude the following items from processing:
exclude:
  - jekyll-theme-spectral-deluxe
  - LICENSE.txt
  - README.md
  - demo_images

# DEMO SITE BUILD SETTINGS

# NOTE: Only include this demo content when building the theme's demo site.
# include:
#  - demo_images
